### ISSUE TITLE
Speakable fails on Node.js v4.2.1 due to spawh() changes

### ISSUE THREAD

**Issue by francip** [sreuter/node-speakable#13]
Running speakable on Node.js v4.2.1 fails with `[TypeError: options argument must be an object]`. This happens when trying to spawn the `sox` process ([node-speakable.js, line 75](https://github.com/sreuter/node-speakable/blob/master/lib/node-speakable.js#L75)) due to the options argument passed being a string.

The quick fix for this is to change that line to 

`var rec = spawn(self.cmd, self.cmdArgs, {stdio:'pipe'});`

I haven't tested this change on Node.js v0.12.x though.

**Comment by gcrev93** [comment]
I am having the same issue. Have you by any chance fixed it?

**Comment by joestrong** [comment]
@gcrev93 Some people have fix this particular issue, for example https://github.com/ajay-gandhi/node-speakable

I still can't get this library to work however, possibly due to the last commit being 2 years ago

**Comment by Jamil** [comment]
Seems to work once that change is made. Works on node/0.12.7 and node/5.7.0

**Comment by joestrong** [comment]
Yeah the fix does stop the error 
(I think I may have a separate issue)

**Comment by unluddite** [comment]
Has anyone got this working? I'm getting the following error after fixing the "options argument must be an object" error:

internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:907:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)

**Comment by lluiscab** [comment]
It doesn't seem to work in nodejs 7.4.0
