### ISSUE TITLE
Always "onSpeachReady"

### ISSUE THREAD

**Issue by CezarLuiz0** [sreuter/node-speakable#7]
Hi! I use Ubuntu and I'm trying use this lib.

I'm using [this example](https://github.com/sreuter/node-speakable) and the log is always "onSpeechReady".

![captura de tela de 2014-05-26 22 59 12](https://cloud.githubusercontent.com/assets/954889/3086819/bdfb156e-e543-11e3-816b-3f59827a4753.png)

I speak anything but nothing happens.

Any idea? My notebook is a Dell and it has a mic.

**Comment by octalmage** [comment]
You need to set a higher threshold, the script isn't detecting a break in the noise. Try this: 

```
var speakable = new Speakable({key: API_KEY},{threshold: "5%"});
```

This worked great for me!
